[package]
name = "archer-thrift"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
archer-thrift-derive = { path = "../archer-thrift-derive" }
thrift = "0.17.0"
