[package]
name = "archer-thrift"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
thrift = "0.16.0"

[build-dependencies]
walkdir = "2.3.2"
which = "4.2.5"
