[package]
name = "archer"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.61"
prost = "0.11.0"
prost-types = "0.11.1"

[profile.release]
lto = true
strip = true

[build-dependencies]
prost-build = "0.11.1"
