[workspace]
members = ["archer-http", "archer-proto", "archer-thrift", "archer-thrift-derive", "tracing-quiver"]

[workspace.package]
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"


[package]
name = "archer"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.65"
archer-http = { path = "archer-http" }
archer-proto = { path = "archer-proto" }
archer-thrift = { path = "archer-thrift" }
base64 = "0.13.0"
bimap = "0.6.2"
bytes = "1.2.1"
futures-util = { version = "0.3.24", features = ["sink"] }
hex = "0.4.3"
itoa = "1.0.3"
mime = "0.3.16"
once_cell = "1.15.0"
opentelemetry = { version = "0.18.0", features = ["rt-tokio", "trace"] }
opentelemetry-semantic-conventions = "0.10.0"
phf = { version = "0.11.1", features = ["macros"] }
quinn = { version = "0.8.5", default-features = false, features = ["ring", "tls-rustls"] }
rand = "0.8.5"
rcgen = "0.10.0"
rmp-serde = "1.1.1"
rusqlite = { version = "0.28.0", features = ["array", "bundled", "time", "trace"] }
rustls = "0.20.6"
rustls-pemfile = "1.0.1"
ryu = "1.0.11"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
snap = "1.0.5"
thiserror = "1.0.37"
time = { version = "0.3.14", features = ["serde"] }
tokio = { version = "1.21.2", features = ["fs", "macros", "rt-multi-thread", "sync"] }
tokio-shutdown = "0.1.3"
tokio-util = { version = "0.7.4", features = ["codec", "net"] }
tracing = "0.1.36"
tracing-opentelemetry = "0.18.0"
tracing-subscriber = "0.3.15"
unidirs = "0.1.0"

[dev-dependencies]
serde_urlencoded = "0.7.1"

[build-dependencies]
mime_guess = "2.0.4"
quote = { version = "1.0.21", default-features = false }
regex = "1.6.0"
siphasher = "0.3.10"
walkdir = "2.3.2"

[profile.release]
lto = true
strip = true
