[package]
name = "archer"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.61"
axum = { version = "0.5.15", features = ["http2"] }
prost = "0.11.0"
prost-types = "0.11.1"
serde = { version = "1.0.143", features = ["derive"] }
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.3.4", features = ["fs", "trace"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"

[profile.release]
lto = true
strip = true

[build-dependencies]
prost-build = "0.11.1"
