[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "MIT",
]
exceptions = [
    { allow = ["MPL-2.0"], name = "option-ext" },
    { allow = ["OpenSSL"], name = "ring" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[licenses.private]
ignore = true

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    "base64@0.21",
    "hashbrown@0.12",
    "hashbrown@0.14",
    "indexmap@1",
    "siphasher@0.3",
    "sync_wrapper@0.1",
    "tower@0.4",
]
skip-tree = [
    { crate = "windows-sys@0.48", depth = 3 },
    { crate = "windows-sys@0.52", depth = 3 },
]
