[licenses]
allow = []
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["AGPL-3.0"], name = "archer" },
    { allow = ["AGPL-3.0"], name = "archer-http" },
    { allow = ["AGPL-3.0"], name = "archer-proto" },
    { allow = ["AGPL-3.0"], name = "archer-thrift" },
    { allow = ["AGPL-3.0"], name = "archer-thrift-derive" },
    { allow = ["OpenSSL"], name = "ring" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    { name = "base64", version = "=0.13.1" },
    { name = "bitflags", version = "=1.3.2" },
    { name = "hermit-abi", version = "=0.2.6" },
    { name = "ordered-float", version = "=2.10.0" },
    { name = "redox_syscall", version = "=0.2.16" },
    { name = "syn", version = "=1.0.109" },
]
skip-tree = [
    { name = "windows-sys", version = "=0.42.0", depth = 2 },
    { name = "windows-sys", version = "=0.45.0", depth = 2 },
]
