[licenses]
allow = []
allow-osi-fsf-free = "both"
exceptions = [
    { allow = ["MPL-2.0"], name = "option-ext" },
    { allow = ["OpenSSL"], name = "ring" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[licenses.private]
ignore = true

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
skip = [
    { name = "bitflags", version = "1" },
    { name = "hashbrown", version = "0.12" },
    { name = "indexmap", version = "1" },
    { name = "ring", version = "0.16" },
    { name = "siphasher", version = "0.3" },
    { name = "socket2", version = "0.4" },
    { name = "spin", version = "0.5" },
    { name = "untrusted", version = "0.7" },
]
skip-tree = [
    { name = "windows-sys", version = "0.48", depth = 3 },
]
