[package]
name = "archer-http"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.66"
axum = { version = "0.5.17", features = ["headers", "http2"] }
num-traits = { version = "0.2.15", features = ["i128"] }
ordered-float = "3.3.0"
serde = { version = "1.0.145", features = ["derive"] }
thiserror = "1.0.37"
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["compression-gzip", "decompression-gzip", "trace"] }
