[package]
name = "archer-proto"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prost = "0.11.3"
prost-types = "0.11.2"
tonic = { version = "0.8.3", features = ["gzip"] }

[build-dependencies]
tonic-build = "0.8.4"
