[package]
name = "archer-proto"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
prost = "0.11.0"
prost-types = "0.11.1"
tonic = { version = "0.8.1", features = ["gzip"] }

[build-dependencies]
tonic-build = "0.8.0"
