[package]
name = "tracing-archer"
version.workspace = true
authors.workspace = true
edition.workspace = true
license = "MIT"

[dependencies]
once_cell = "1.18.0"
postcard = { version = "1.0.6", default-features = false, features = ["use-std"] }
quanta = "0.11.1"
quinn = { version = "0.10.2", default-features = false, features = ["runtime-tokio", "tls-rustls"] }
rand = "0.8.5"
rustls = "0.21.6"
rustls-pemfile = "1.0.3"
serde = { version = "1.0.183", features = ["derive", "rc"] }
snap = "1.1.0"
thiserror = "1.0.44"
time = { version = "0.3.25", features = ["serde"] }
tokio = { version = "1.29.1", features = ["net", "sync", "time"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
webpki = { version = "0.22.0", features = ["std"] }

[dev-dependencies]
anyhow = "1.0.72"
tokio = { version = "1.29.1", features = ["fs", "macros", "rt-multi-thread", "time"] }
