[package]
name = "tracing-quiver"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
once_cell = "1.14.0"
quanta = "0.10.1"
quinn = { version = "0.8.5", default-features = false, features = ["ring", "tls-rustls"] }
rand = "0.8.5"
rmp-serde = "1.1.0"
rustls = "0.20.6"
rustls-pemfile = "1.0.1"
serde = { version = "1.0.144", features = ["derive", "rc"] }
snap = "1.0.5"
thiserror = "1.0.33"
time = { version = "0.3.14", features = ["serde"] }
tokio = { version = "1.21.0", features = ["sync", "time"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
webpki = "0.22.0"

[dev-dependencies]
anyhow = "1.0.63"
tokio = { version = "1.21.0", features = ["fs", "macros", "rt-multi-thread", "time"] }
