[package]
name = "tracing-quiver"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
once_cell = "1.13.1"
postcard = { version = "1.0.2", default-features = false, features = ["use-std"] }
quanta = "0.10.1"
quinn = { version = "0.8.5", default-features = false, features = ["ring", "tls-rustls"] }
rand = "0.8.5"
rustls = "0.20.6"
rustls-pemfile = "1.0.1"
serde = { version = "1.0.144", features = ["derive"] }
thiserror = "1.0.32"
time = { version = "0.3.14", features = ["serde"] }
tokio = { version = "1.20.1", features = ["sync"] }
tracing = "0.1.36"
tracing-subscriber = "0.3.15"
webpki = "0.22.0"

[dev-dependencies]
anyhow = "1.0.62"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread", "time"] }
